[package]
name = "swoooop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
one-eyed-jack = { git = "https://github.com/eyepatchSamurAI/one-eyed-jack.git", branch = "main" }
